FROM apache/airflow:2.9.2-python3.11
USER root
RUN apt-get update && apt-get install -y --no-install-recommends docker.io && rm -rf /var/lib/apt/lists/*
RUN python -m venv /opt/mlvenv
COPY requirements.txt /tmp/ml-requirements.txt
RUN /opt/mlvenv/bin/pip install --no-cache-dir -r /tmp/ml-requirements.txt
USER airflow
