channels:
- conda-forge
dependencies:
- python=3.11.16
- pip<=24.0
- pip:
  - mlflow==2.14.1
  - scikit-learn==1.5.0
  - numpy==1.26.4
  - pandas==2.2.2
  - scipy==1.13.1
  - joblib==1.4.2
  - setuptools==70.1.0
  - SQLAlchemy==2.0.31
name: mlflow-env
